services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    platform: linux/amd64
    environment:
      - HBASE_THRIFT_HTTP=false
    ports:
      - "16010:16010"  # Web UI
      - "9090:9090"    # Thrift
      - "2181:2181"    # ZooKeeper
    volumes:
      - hbase_data:/hbase
 
volumes:
  mongodb_data:
  redis_data:
  hbase_data: