version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16010:16010"  # Web UI
      - "9090:9090"    # Thrift
      - "2181:2181"    # ZooKeeper inside

volumes:
  mongodb_data:
  redis_data:
  hbase_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/hbase/data
      o: bind