
services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./log4j.properties:/etc/kafka/log4j.properties

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_basedatos
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: deeplearning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  metabase:
    image: metabase/metabase:v0.45.2
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_CONNECTION_URI: jdbc:mysql://mysql:3306/mi_basedatos?useSSL=false&serverTimezone=UTC
      MB_DB_USER: proyecto
      MB_DB_PASS: deeplearning
    depends_on:
      - mysql

volumes:
  mongodb_data:
  mysql_data:
  zookeeper_data:
  kafka_data:
  metabase_data:
    
